/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.programming.webinar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BowlingTest {
    @Test void someLibraryMethodReturnsTrue() {
        Bowling classUnderTest = new Bowling();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
