/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.programming.webinar;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class BowlingTest {
    @Test void score_returns7_when6Plus1PinsKnockedDownInAFrame() {
        Bowling bowling = new Bowling();
        int expected = 7;
        List<String> frames = new ArrayList<>();
        frames.add("6/1");
        int actual = bowling.score(frames);

        assertEquals(expected, actual);
    }
}
