/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.programming.webinar;

public class Bowling {
    public boolean someLibraryMethod() {
        return true;
    }
}
