/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.programming.webinar;

import java.util.List;

public class Bowling {
    public int score(List<String> frames) {
        return 7;
    }
}
