/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pair.programming.webinar;

import java.util.List;

public class Bowling {
    public int score(List<String> frames) {
        int acc = 0;
        int index = 0;
        for (String frame :
                frames) {
            index++;
            int localScore = frameScore(frame);
            if (localScore == 10) {
                   int nextThrowScore = Integer.parseInt(frames.get(index).split("/")[0]);
                   acc += nextThrowScore + 10;
            } else {
            acc += localScore;
            }
        }
        return acc;
    }

    private int frameScore(String frame) {
        String[] throwArray = frame.split("/");
        return Integer.parseInt(throwArray[0]) + Integer.parseInt(throwArray[1]);
    }
}
